env:
  browser: true
  es2021: true
  node: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "tsconfig.eslint.json"
rules:
  {
    "@typescript-eslint/quotes": "off",
    "@typescript-eslint/semi": "off",
    "@typescript-eslint/strict-boolean-expressions": "off",
    "@typescript-eslint/space-before-function-paren": "off",
    "@typescript-eslint/consistent-indexed-object-style": "off",
    "@typescript-eslint/no-unnecessary-type-constraint": "off",
    "@typescript-eslint/comma-dangle": "off",
    "@typescript-eslint/array-type": "off",
    "@typescript-eslint/no-confusing-void-expression": "off",
    "@typescript-eslint/member-delimiter-style":
      [
        "error",
        {
          "multiline": { "delimiter": "semi", "requireLast": true },
          "singleline": { "delimiter": "semi", "requireLast": false },
          "multilineDetection": "brackets",
        },
      ],
  }
